site_name: 'ADMIN-238: Just Enough Kubernetes'
site_author: Cloudera Education
copyright: Cloudera Inc. 2025
theme:
    name: material
    logo: assets/images/logo-cloudera-white.svg
    palette:
    - scheme: default
      primary: #FFFFFF
      accent: #121212
      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
    features:
    - content.code.annotate
    - content.code.copy

docs_dir: '../exercises'
site_dir: '../build/AMP/exercises'
extra_css:
  - stylesheets/extra.css
use_directory_urls: false


nav:
    - 'Course Overview': 'README.md'
    - 'Table of Contents': 'guide/README.md'
    - '01 Course Introduction':
      - '01-01 Course Introduction': 'guide/01-01/README.md'
      - '01-02 Getting Aboard': 'guide/01-02/README.md'
    - '02 Get Aboard':
      - '02-01 Get Aboard': 'guide/02-01/README.md'
      - '02-02 Get Aboard': 'guide/02-02/README.md'
      - '02-03 Bookmarking Cloudera Resources': 'guide/02-03/README.md'
    - '03 Design Principles for Kubernetes':
      - '03-01 Design Principles for Kubernetes': 'guide/03-01/README.md'
      - '03-02 Reviewing Kubernetes Documentation': 'guide/03-02/README.md'
    - '04 Access and Interact':
      - '04-01 Access and Interact': 'guide/04-01/README.md'
      - '04-02 Installing minikube for macOS': 'guide/04-02/README.md'
      - '04-03 Installing minikube for Windows': 'guide/04-03/README.md'
      - '04-04 Running minikube': 'guide/04-04/README.md'
    - '05 Microservices':
      - '05-01 Microservices': 'guide/05-01/README.md'
      - '05-02 Running Docker Commands': 'guide/05-02/README.md'
      - '05-03 Building a Microservice': 'guide/05-03/README.md'
    - '06 Architecture for Kubernetes Resources':
      - '06-01 Architecture for Kubernetes Resources': 'guide/06-01/README.md'
      - '06-02 Architecture for Kubernetes Resources': 'guide/06-02/README.md'
      - '06-03 Running Pods and Services': 'guide/06-03/README.md'
      - '06-04 Inspecting the Kubernetes Dashboard': 'guide/06-04/README.md'
    - '07 Kubernetes Manifest Files':
      - '07-01 Kubernetes Manifest Files': 'guide/07-01/README.md'
      - '07-02 Creating Deployments': 'guide/07-02/README.md'
      - '07-03 Inspecting Deployments': 'guide/07-03/README.md'
    - '08 Architecture for Kubernetes Cluster':
      - '08-01 Architecture for Kubernetes Cluster': 'guide/08-01/README.md'
      - '08-02 Architecture for Kubernetes Cluster': 'guide/08-02/README.md'
    - '09 Architecture for Kubernetes Control Plane':
      - '09-01 Architecture for Kubernetes Control Plane': 'guide/09-01/README.md'
      - '09-02 Inspecting the Control Plane': 'guide/09-02/README.md'
    - '10 Next Steps':
      - '10-01 Next Steps': 'guide/10-01/README.md'
    - 'Appendix-A Cloudera Support':
      - 'A-01 Cloudera Support': 'guide/A-01/README.md'
      - 'A-02 Bookmarking Cloudera Resources': 'guide/A-02/README.md'



markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - toc:
      toc_depth: 3
  - sane_lists: {}


plugins:
  - search
  - markdownextradata: {}
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 80%
      height: auto
      zoomable: true
      draggable: true

extra:
  github:
    url: "https://github.com/sanketmote05/portfolio-website"
